FROM python:3.10

# 작업 디렉토리 설정
WORKDIR /app
# 의존성 설치
COPY requirements.txt .
RUN apt-get update
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
# 소스 코드 복사
COPY . .

# 포트 오픈
EXPOSE 8000

# Dockerfile-prod
CMD ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000", "--workers=4", "--threads=2"]