# MQTT Plugin 설정
mqtt.listeners.tcp.default = 1883
mqtt.allow_anonymous = false
mqtt.default_user = sa
mqtt.default_pass = 1234
mqtt.vhost = /
mqtt.exchange = amq.topic
mqtt.subscription_ttl = 86400000
mqtt.prefetch = 10

# Management Plugin
management.tcp.port = 15672

